language: python
python:
  - "3.8"
  - "3.7"
  - "2.7"
install:
  pip install -r requirements.txt
services:
  - mysql
before_script: sudo mysql -e 'create database testing;'
dist: precise
script:
  - python -m unittest discover
notifications:
  email: false