language: python
python:
  - "3.8"
  - "3.7"
install:
  pip install -r requirements.txt
services:
  - mysql
addons:
  apt:
    sources:
      - mysql
    packages:
      - mysql-server
      - mysql-client
before_script:
#  - pylint views
#  - pylint models
#  - pylint rest
#  - pylint service
#  - pylint tests
  - python app.py
script:
  - python -m unittest discover
notifications:
  email: false