language: python
python:
  - "3.8"
  - "3.7"
install:
  pip install -r requirements.txt
services:
  - mysql
before_install:
  - sudo mysql -e "use mysql; update user set authentication_string=PASSWORD('root') where User='root'; update user set plugin='mysql_native_password';FLUSH PRIVILEGES;"
  - sudo mysql_upgrade -u root -p root
  - sudo service mysql restart
script:
  - pylint views
  - pylint --load-plugins pylint_flask_sqlalchemy models
  - pylint rest
  - pylint service
  - pylint tests
  -  python app.py
  - python -m unittest discover
notifications:
  email: false