language: python
python:
  - "3.8"
  - "3.7"
install:
  pip install -r requirements.txt
services:
  - mysql
addons:
  apt:
    sources:
      - mysql-5.7-trusty
    packages:
      - mysql-server
      - mysql-client
before_script: sudo mysql -e 'create database if not exists testing;'
script:
  - python -m unittest discover
notifications:
  email: false