"""Cascade

Revision ID: 44c8c62ae926
Revises: 
Create Date: 2021-11-30 12:59:14.771111

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '44c8c62ae926'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('university', 'average_salary')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('university', sa.Column('average_salary', mysql.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
