"""Cascade

Revision ID: 9270b94c2c4e
Revises: 44c8c62ae926
Create Date: 2021-11-30 13:04:38.414237

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9270b94c2c4e'
down_revision = '44c8c62ae926'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('teacher_ibfk_1', 'teacher', type_='foreignkey')
    op.create_foreign_key(None, 'teacher', 'university', ['university_id'], ['id'], ondelete='CASCADE')
    op.add_column('university', sa.Column('average_salary', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('university', 'average_salary')
    op.drop_constraint(None, 'teacher', type_='foreignkey')
    op.create_foreign_key('teacher_ibfk_1', 'teacher', 'university', ['university_id'], ['id'])
    # ### end Alembic commands ###
